### ISSUE TITLE
clearfixをモダンブラウザ用に変更する

### ISSUE THREAD

**Issue by shunpei-torii** [oRoFE/oRoFE.github.io#16]
clearfixをそろそろ更新してもいいんじゃないかと思いました。
オロのだと `content:".";` が結構悪さしてた気がします。

http://coliss.com/articles/build-websites/operation/css/css-latest-clearfix.html
IE8以上であれば以下のCSSで問題ありません。（IETesterで確認済み）
```
.clearfix:after {
  content: "";
  display: block;
  clear: both;
}
```

**Comment by shunpei-torii** [comment]
- [x] ja
- [ ] zh
- [ ] en
- [ ] vn

**Comment by YusukeNakaya** [comment]
これ実装済みだね、CLOSEでいいね。
