### ISSUE TITLE
リセットスタイル変更: svg

### ISSUE THREAD

**Issue by shunpei-torii** [oRoFE/oRoFE.github.io#17]
リセットスタイルの
```
img{vartical-align: bottom}
```
を、
```
img, svg{vartical-align: top}
```
に変えたいです。SVG追加したいのと、bottomよりはtopのほうが使いやすいのかなと思いました。

**Comment by YusukeNakaya** [comment]
`img,svg{vartical-align:middle;}`の方が使いやすいんじゃないだろうか。
例えば、文章の中にアイコン画像が入ってくる場合など。
bottomが使いにくいと思った理由は何だっけ？

**Comment by shunpei-torii** [comment]
リセットスタイルに、 `ol li{list-style-type:none;}` を追加したいのですが、どうでしょうか。

**Comment by YusukeNakaya** [comment]
リストスタイルはブラウザ差異が大きく、事実上、デフォルトで使う事はほとんど無いよね。
いいと思います。
issue分ける？

**Comment by shunpei-torii** [comment]
>issue分ける？

そうですね。分けたほうがよさそうですね。
一番上の

>img, svg{vartical-align: top}

この件は解決したんでしたっけ？

**Comment by koya-iwasaki** [comment]
`vartical-align: top` へのこだわりはそんなにないので、bottomやmiddleでもいいです。

**Comment by shunpei-torii** [comment]
了解です。
では一旦このIssueはクローズして、新しく立てますね。

**Comment by koya-iwasaki** [comment]
あ、これ解決はしてません。本質は、svgを追加するかどうかです。

**Comment by YusukeNakaya** [comment]
`img,svg{vartical-align:middle;}` でいこうと思うけど、どうかな？

**Comment by ktsn** [comment]
良いと思います。 :+1:

**Comment by YusukeNakaya** [comment]
実装
