### ISSUE TITLE
【議論】reset.cssについて

### ISSUE THREAD

**Issue by shunpei-torii** [oRoFE/oRoFE.github.io#20]
hrとlegendが `display:none;` になってるのって どんな理由からでしたっけ？

`hr,legend{display:none;}`

**Comment by ktsn** [comment]
外しても良いような気がしますね。どうなんでしょうか？ @oRoFE/owners

**Comment by YusukeNakaya** [comment]
遺産っぽいので、reset.cssから消してしまってもよいでしょう。
