### ISSUE TITLE
clearfixしてなかった

### ISSUE THREAD

**Issue by noliaki** [oRoFE/oRoFE.github.io#58]
コンテンツの`inner`に`aside`と`article`がfloatしてるけど、clearしてなかった…。
新卒課題でも突っ込んでた部分だけに恥ずかしい…！

**Comment by YusukeNakaya** [comment]
いや、意図的にしてなかったよｗ
する必要がないなら、しなくてもいいんじゃないかい？

**Comment by noliaki** [comment]
@YusukeNakaya 

> いや、意図的にしてなかったよｗ
> する必要がないなら、しなくてもいいんじゃないかい？

え！？
そうなんですか？
基本、floatしてるモノの親には必ずclearfixしてました…。
floatしてる親の高さが取れない（0になる）し、その後の要素が頑張って回り込もうとするしレイアウト崩れの原因の一番あるあるだと思ってたんですが…。

必要ない、と判断するのってどんなときですか？

**Comment by YusukeNakaya** [comment]
floatしてる親の高が必要だったり、floatを起因とするレイアウト崩れが起きている場合は、clearfixする。そうじゃなければ入れてない。
確かに予防として常時入れておくのはいいかもしれないけど、必要ないのだから少し違和感。
これはコーディングスタイルに寄るのかな、みんなどうしてる？

... 関係ないけどインフル予防注射も必要性を感じないのでやってない

**Comment by ktsn** [comment]
むしろ float の状態が解除されないままなのが気持ち悪いですねー。

**Comment by YusukeNakaya** [comment]
解除という意味では`footer`で`clear: both;`してるけど、
`.inner`単体で解除されてないのが気持ち悪い感じがするのかい？
気持ち悪さの原因は、
「親の高さが取得できない不安感」「崩れるかもしれない不安感」とかかな？

**Comment by koya-iwasaki** [comment]
僕もfloatしてる親要素では基本clearfixしてますね。backgroundあってもなくても正常に動くようにですかね。
もちろんfloatしてないところには付けませんが。clearfixしちゃうと擬似要素1つないし2つ使えなくなっちゃうデメリットはありますよね。

**Comment by ktsn** [comment]
@YusukeNakaya 
`clear: both;` してるならそれはそれで良いと感じます。コード読んでなかったので `clear` も無いのかと思ってました。
うしろの要素で `clear` してるならどちらかといえば clearfix は無くてもいい派ですね。

**Comment by noliaki** [comment]
@koya-iwasaki 
あまり出会ったことなくて わからんのだけど、
例えば `<div class="inner clearfix">`で

```css
.inner {
}

.clearfix {
}

.clearfix:after {
  /*clearするスタイル*/
}

.clearfix:before {
  /*clearするスタイル*/
}
```

の場合だと `inner` に対しての擬似要素も使えなくなるってこと？

**Comment by koya-iwasaki** [comment]
@noliaki そうですね。擬似要素で装飾しようとしたらclearfixが効かなくなって崩れたっていうことが確かあったので。タグ増やすとかすれば回避できますが。でも言うほどデメリットは感じてません。

**Comment by noliaki** [comment]
これはバグでも間違いでも無いことが わかったのでcloseします。
まぁ時と場合で使っていくってことで。（バメンで！）

個人的にはそのブロックのことはそのブロック内で解決しといた方がいいかなーと思いました。
（次に来る要素に影響を与えないように）
