### ISSUE TITLE
リセットスタイル変更： ol

### ISSUE THREAD

**Issue by shunpei-torii** [oRoFE/oRoFE.github.io#60]
```
ul li{list-style-type:none;}
```

を

```
ul li,ol li{list-style-type:none;}
```

に変更したい。

**Comment by noliaki** [comment]
@shunpei-torii 
何でなのか理由が知りたいです。

**Comment by shunpei-torii** [comment]
@noliaki 
デフォルトのものを使うことがないからですね。
どうでしょう？

**Comment by noliaki** [comment]
そうなのね。
俺は結構使ってたりしてたから、意外。

反対ではないので、他の人が問題なければ 🙆  です

**Comment by YusukeNakaya** [comment]
1. 基本的に、デザインの都合上、デフォルトマークを使う事がほぼない。
2. デフォルトマークを使用する場合、何を使うかを明示的に指定した方がいい。

という理由から、鳥居くんの提案を採用したいと思うけど、どうかな？

**Comment by YusukeNakaya** [comment]
実装
