### ISSUE TITLE
ベトナム語版のHTML5タグゲームが翻訳されてない

### ISSUE THREAD

**Issue by YusukeNakaya** [oRoFE/oRoFE.github.io#61]
ベトナム語版のHTML5タグゲームが翻訳されてない。
そもそも翻訳データって、あったっけ？

**Comment by shunpei-torii** [comment]
@YusukeNakaya 
翻訳データもらってませんでした。先ほどコミュニケーターの方に翻訳を依頼したので近日中にはもらえるかと思います。

**Comment by shunpei-torii** [comment]
翻訳データ来ました。

[CODING CSS GUIDELINE-updated 20160405.pptx](https://github.com/oRoFE/oRoFE.github.io/files/301735/CODING.CSS.GUIDELINE-updated.20160405.pptx)

**Comment by ktsn** [comment]
#64
